# DICHIARAZIONE CONFIG MAP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-deployment-prod-portale-1
data:
  server.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <!-- Connettore HTTP sulla porta 80 -->
        <Connector port="80" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps"
                unpackWARs="true" autoDeploy="true">
          </Host>
        </Engine>
      </Service>
    </Server>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-deployment-prod-portale-2
data:
  server.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <!-- Connettore HTTP sulla porta 80 -->
        <Connector port="80" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps"
                unpackWARs="true" autoDeploy="true">
          </Host>
        </Engine>
      </Service>
    </Server>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-deployment-prod-portale-3
data:
  server.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <!-- Connettore HTTP sulla porta 80 -->
        <Connector port="80" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps"
                unpackWARs="true" autoDeploy="true">
          </Host>
        </Engine>
      </Service>
    </Server>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-deployment-prod-portale-4
data:
  server.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Server port="8005" shutdown="SHUTDOWN">
      <Service name="Catalina">
        <!-- Connettore HTTP sulla porta 80 -->
        <Connector port="80" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="443" />
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps"
                unpackWARs="true" autoDeploy="true">
          </Host>
        </Engine>
      </Service>
    </Server>
---

# DICHIARAZIONE SECRET
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials   # questo nome va referenziato nel Deployment
type: Opaque
stringData:
  username: postgres           # sostituisci con l'username che vuoi usare
  password: appdb              # sostituisci con la password reale


# DICHIARAZIONE DEPLOYMENT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-prod-portale-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-app-prod-portale-1
  template:
    metadata:
      labels:
        app: deployment-app-prod-portale-1
    spec:
      volumes:
        - name: webapps
          emptyDir: {}  # volume temporaneo per condividere la WAR tra initContainer e Tomcat
        - name: tomcat-config-volume
          configMap:
            name: config-map-deployment-prod-portale-1  # ConfigMap per server.xml

      initContainers:
        - name: download-war
          image: alpine/git
          command:
            - sh
            - -c
            - |
              if [ -d /tmp/app ]; then
                cd /tmp/app && git pull
              else
                git clone http://192.168.36.245/proxlab-kubernetes-infrastructure/deployment-app-prod-portale-1.git /tmp/app
              fi
              cp /tmp/app/hello.war /webapps/
          volumeMounts:
            - name: webapps
              mountPath: /webapps

      containers:
        - name: pod-prod-portale-1
          image: tomcat:9.0.115-jdk17-corretto-al2:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "prod-postgres.postgres-operator.svc.cluster.local"  # nome del Service Postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con password
                  key: password
          volumeMounts:
            - name: webapps
              mountPath: /usr/local/tomcat/webapps
            - name: tomcat-config-volume
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-prod-portale-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-app-prod-portale-2
  template:
    metadata:
      labels:
        app: deployment-app-prod-portale-2
    spec:
      volumes:
        - name: webapps
          emptyDir: {}  # volume temporaneo per condividere la WAR tra initContainer e Tomcat
        - name: tomcat-config-volume
          configMap:
            name: config-map-deployment-prod-portale-2  # ConfigMap per server.xml

      initContainers:
        - name: download-war
          image: alpine/git
          command:
            - sh
            - -c
            - |
              if [ -d /tmp/app ]; then
                cd /tmp/app && git pull
              else
                git clone http://192.168.36.245/proxlab-kubernetes-infrastructure/deployment-app-prod-portale-2.git /tmp/app
              fi
              cp /tmp/app/hello.war /webapps/
          volumeMounts:
            - name: webapps
              mountPath: /webapps

      containers:
        - name: pod-prod-portale-2
          image: tomcat:9.0.115-jdk17-corretto-al2:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "prod-postgres.postgres-operator.svc.cluster.local"  # nome del Service Postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con password
                  key: password
          volumeMounts:
            - name: webapps
              mountPath: /usr/local/tomcat/webapps
            - name: tomcat-config-volume
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-prod-portale-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-app-prod-portale-3
  template:
    metadata:
      labels:
        app: deployment-app-prod-portale-3
    spec:
      volumes:
        - name: webapps
          emptyDir: {}  # volume temporaneo per condividere la WAR tra initContainer e Tomcat
        - name: tomcat-config-volume
          configMap:
            name: config-map-deployment-prod-portale-3  # ConfigMap per server.xml

      initContainers:
        - name: download-war
          image: alpine/git
          command:
            - sh
            - -c
            - |
              if [ -d /tmp/app ]; then
                cd /tmp/app && git pull
              else
                git clone http://192.168.36.245/proxlab-kubernetes-infrastructure/deployment-app-prod-portale-3.git /tmp/app
              fi
              cp /tmp/app/hello.war /webapps/
          volumeMounts:
            - name: webapps
              mountPath: /webapps

      containers:
        - name: pod-prod-portale-3
          image: tomcat:9.0.115-jdk17-corretto-al2:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "prod-postgres.postgres-operator.svc.cluster.local"  # nome del Service Postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con password
                  key: password
          volumeMounts:
            - name: webapps
              mountPath: /usr/local/tomcat/webapps
            - name: tomcat-config-volume
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-prod-portale-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-app-prod-portale-4
  template:
    metadata:
      labels:
        app: deployment-app-prod-portale-4
    spec:
      volumes:
        - name: webapps
          emptyDir: {}  # volume temporaneo per condividere la WAR tra initContainer e Tomcat
        - name: tomcat-config-volume
          configMap:
            name: config-map-deployment-prod-portale-4  # ConfigMap per server.xml

      initContainers:
        - name: download-war
          image: alpine/git
          command:
            - sh
            - -c
            - |
              if [ -d /tmp/app ]; then
                cd /tmp/app && git pull
              else
                git clone http://192.168.36.245/proxlab-kubernetes-infrastructure/deployment-app-prod-portale-4.git /tmp/app
              fi
              cp /tmp/app/hello.war /webapps/
          volumeMounts:
            - name: webapps
              mountPath: /webapps

      containers:
        - name: pod-prod-portale-4
          image: tomcat:9.0.115-jdk17-corretto-al2:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "prod-postgres.postgres-operator.svc.cluster.local"  # nome del Service Postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Secret con password
                  key: password
          volumeMounts:
            - name: webapps
              mountPath: /usr/local/tomcat/webapps
            - name: tomcat-config-volume
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml

